### PR TITLE
[Bounty] GUI enhancements

### PR DESCRIPTION
**Pull request by jmankhan**
Completed:
source code panel
output panel
toggle between stdout and gui for output
link to github (right click context menu)
added a TestUtilIO with tests for nonGUI methods
Source code is non-editable but copyable via ctrl+A + ctrl+C
Source code scrolls down past the copyright notice

### CODE REVIEW

**Comment by jmankhan** [comment]
Just saw your update in the google groups! I can work on those changes and  make a new PR if you would like

**Comment by lessthanoptimal** [comment]
Let's do that, but I'll take a quick look at this one.

**Comment by lessthanoptimal** [comment]
Think I caught one issue.   I'm guessing that the system output stream is not invoked inside the AWT event dispatching thread.  In that case line 54 of OutputStreamCapturer should invoked SwingUtilities.invokeLater().

**Comment by lessthanoptimal** [comment]
The tab for each panel requires you to redirect the stdout for each process individually.  This can be accomplished by providing your own streams to JavaRuntimeLauncher before the process is launched.  See setPrintOut() and setPrintErr().

**Pull request merged**
