### PR TITLE
Fixing small type errors in the documentation of BoofTesting

### PR DESCRIPTION
**Pull request by boechat107**
The type errors seem to have been forgotten copy & paste mistakes.

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
Any chance you could do this in the latest SNAPSHOT?  I would just do the change myself but though you might want to have the modification with name in the history git.

**Comment by boechat107** [comment]
Sure, I can do it! But it's fine if it is easier for you to change it yourself. Thanks for asking!

**Comment by boechat107** [comment]
Ops, I tried the easiest way, but it seems that something has changed.

**Comment by boechat107** [comment]
Done!

**Pull request merged**
