### PR TITLE
Adjustable bit size binary fiducials

### PR DESCRIPTION
**Pull request by npahucki**
Allows Binary Fiducials to work with 3, 4, or 5 squares in the grid. The reason for this is that in some uses cases (mine is one) the 4096 elements that 4x4 gives you is simply not enough. In other cases, you may need just a few but want better recognition (using 3x3). 

This pull request adds the required logic for this functionality, and also modifies the command line tools in  the applications module to expose the functionality. 

In particular, the CreateFiducialSquareBinaryEPS now takes an optional parameter --BinaryGridWidth which can be set to 3, 4 or 5. This will generate the binary fiducials using the specified parameter. Additionally, the WebcamTrackFiducial accepts an optional parameter --GridWidth, which may be 3, 4, 5 or ALL. If one of 3,4,5 are specified, then the detector will only work grids of that size. If ALL is specified, then the camera will detect all 3 types simultaneously, even if all present in the camera at the same time. 

** All unit tests still pass in the recognition module **

I hope the community finds this useful, and thank you for putting together this great and VERY well documented project.

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
I've started the process of merging this in. Looks good so far and doesn't appear to break anything!  Will be making a few changes before it gets merged into the master branch, mostly aesthetic changes.

**Comment by lessthanoptimal** [comment]
Got a couple of comments:
1) The black border's relative size changes depending on the inner grid.  If you make it skinnier it losses its ability to be reliably detected at an angle.  Did a bit of experimenting with that and converged to the same conclusion that the ARToolkit guys did.  I think I'll make it user configurable.
2) Is the combined detector which searches for grids of size 3,4,5 useful for your application?  That's an inefficient (but much easier) way to go about it, but in noisier environments the same square will have multiple returns.

**Comment by npahucki** [comment]
1) I was having problems doing the detection when the black border was constant and I was trying to keep things as close a possible to the original implementation (which made the border a multiple of the fiducial square). You know the system much better than I, so if you can get it to work with a constant size border or user settable border and it works better - great!
2) It's useful for me in my application - but I'm running detection on still photos so in inefficiency is not a big deal. I included it in the webcam app just because it makes testing the three sizes easier - you can hold any up to the camera and it works regardless. It occurred to me that there are much more efficient ways to do it, but it was the what I could do in the time I have available. I'm interested in seeing how improve upon it.

**Comment by lessthanoptimal** [comment]
I think I'm going to punt the multi-fiducial detector for now.  To do it properly will take a bit of a redesign and test.  I want to get the next release out sooner than later.  Plus it's very easy to implement that functionality in your code.

Future: Could make the fiducial base class a stand alone function and have each fiducial type implement a common interface that's passed in.

**Pull request merged**
