### PR TITLE
Fixes XYZ <-> RGB and LAB <-> RGB color conversion

### LINKED ISSUE #158: Doubt: incorrect ColorXyz.rgbToXyz conversion?
I'm using the ColorLab.srgbToLab function and it was giving me different values from what I expected. Looking the code, I found the problem might be on the ColorXyz.rgbToXyz function, which is also getting me unexpected values. The rgb to xyz has only the matrix multiplication, the gamma correction is not being applied. 

I don't have a lot of experience with this, but it seems not correct. Am I missing something? I compared the values with: http://www.brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html (and others). The values matches only when gamma=1

The gamma corrections can be found here:
https://en.wikipedia.org/wiki/SRGB#The_sRGB_transfer_function_(%22gamma%22)
and here:
http://www.brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html

### PR DESCRIPTION
**Pull request by lessthanoptimal**
Applies gamma correction to RGB color space and correctly differentiates between RGB and sRGB

### CODE REVIEW

**Review by JairoRotava — CHANGES_REQUESTED** [review]
I think there is a mistake with the functions names (by the way I left some comments as SWAT Brasil - I forgot to switch accounts). I think the separation between srgb and R'G'B is good and clear, but I think they are inverted.
I understand the R'G'B -> CIE XYZ is just the matrix multiplication, just like it was before
When using srgb -> CIE XYZ you should apply the gamma correction: https://en.wikipedia.org/wiki/SRGB

I think the correct is that all methods with rgb in the name should be srgb, and vice versa, to match the implementation.

**Review by JairoRotava — COMMENTED** [review]
I don't think you need to change this file. Once you correct the srgb -> xyz, the gamma function is already inside the ColorXyz file. I understand that srgb -> gamma correction -> R'G'B' -> XYZ -> LAB. The gamma is applied during XYZ conversion, not during LAB.

**Comment by lessthanoptimal** [comment]
I think some renaming should fix things. Keep `rgbToXyz`  then change `srgbToXyz` to `linearRgbToXyz` and apply the same change to all functions with srgb in its name.

**Comment by JairoRotava** [comment]
> I think some renaming should fix things. Keep `rgbToXyz` then change `srgbToXyz` to `linearRgbToXyz` and apply the same change to all functions with srgb in its name.

ok, working on this

**Comment by JairoRotava** [comment]
it is finished, but I can't push it - permission denied. Should I fork and request a PR?

**Comment by lessthanoptimal** [comment]
yeah fork and create the PR to merge into `feature/gamma_correction` thanks!

**Comment by lessthanoptimal** [comment]
I manually merged this into SNAPSHOT after a few additional tweaks. Thanks for all the help!

**Pull request closed without merging**
