### PR TITLE
DelayedImageSequence and MultiView experiments

### PR DESCRIPTION
**Pull request by automenta**
(not production quality)

DelayedImageSequence creates a 1 image delayed image stream from a provided source stream.  this can be used for example to create a virtual stereoscopic pair of cameras from a single camera.  additional features to this could include to not switch to a new image unless it differs beyond a threshold this way it would maintain the last different image rather than just the latest, and to store the last N images, or some function of them.

the multiview reconstruction changes replace some of the data structures with Map<Long,Feature3D> of (short frame, short x, short y) tuples encoded as a 64-bit long.  this allows quicker lookup rather than the iterative scans in the original version

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
Thanks for the pull request! Got a few comments.

* Could you provide an example of this new feature in use? 
  * This will help me better understand what issue you are addressing better.
  * Maybe create a simple toy project on github with a dataset?
* How much of a speed up is using map and how did you test it?
* The PR needs a lot of clean up before it can be accepted.
  * You mentioned that this isn't production quality. Does that mean you are sharing a work in progress?
* Pull requests should be as focused as possible. 
  * Your PR does a lot more than the changes mentioned. 
  * For example, it includes changes to build script and language level. BoofCV has been updated to be compliant 1.9 but the language level is stuck at 1.8 for a while longer.

Thought I would also mention that a simple implementation of sparse bundle adjustment is scheduled to be added into the next release of BoofCV. This should dramatically improve multi-view reconstruction. Currently its quality kinda sucks.

**Comment by automenta** [comment]
id like to build monocular SLAM / SFM system that i can put together with boofcv.  i see several working monocular SLAM systems on youtube and github, particularly "dense SLAM".  but i cant find a pure-java impl of any of them; most are either C/C++ or python and not easily translated to java - for example, they always depend on different lower level libraries (sometimes involving openCV, but always need other libs for whatever openCV isnt providing).  

i know boofcv can implement it just as well if not better, the SFM and odometry demos show it at least halfway there.

the DelayedImageSequence is meant as an adapter to provide stereoscopic input from one camera input.  for example the pointcloud and depth odometry demos which use 2 images or 2 image sequences to compute disparity can be made to function, to at least some degree, from the accumulation of subsequent pairs of  frames from one camera.

but ideally, i imagine some generalization of the multi-view case could handle 1, 2, or N inputs, with frames arriving asynchronously and gracefully adapting to missing or corrupt input as it maintains, as output, a 3d (4d?) scene mesh (not just depth map like the point cloud viewer) and/or odometry model.  in the case of missing or partial configuration parameters (such as camera calibration), a lowest common denominator model can learn to tune for the whatever the current conditions might be - rather than expecting it as initialization parameters as the API currently requires.  boofcv's camera calibration GUIs would become particular ways of interactively accelerating such tuning - but not necessary.

im not suggesting any particular SLAM/SFM algorithm but rather that an ideal boofcv-based API for flexible use of them could/should exist.  and a unified demo of its functionality would cover all boofcv's current SFM/odometry features.

i didnt benchmark the multiview map optimizations but now im more interested in considering the bigger picture.  though i did find the long hash key a clever (though somewhat lossy) way to encode those tuples - in case it ever becomes useful in SFM or other components, my intuition being that the right application of hashing there will provide a significant speedup compared to the original iterative lookups.

one other idea re: SFM -- to use a 3d renderer for testing / tuning / training.  generated artificial scenery can verify the 3d output, and it could also be used in a feedback loop for the model to validate its 3d output by internally rendering it to an image that can be compared, as an image, with the 2d input.  (attached screenshot of a raytracer experiment)

screenshot_2018-03-25_20-36-52

**Comment by lessthanoptimal** [comment]
When I referenced sparse bundle adjustment that's talking about the linear solver used. Almost all large scale bundle adjustment or SLAM type algorithms use some form of that. A dense solver has a runtime complexity of O(N^3) while a sparse one is approximately O(N). That's a bit of an over simplification but you get the idea. BoofCV has everything that you would need expect for a sparse solver and that's schedule to be fixed in the next couple of months.

You might be interested in ValidationBoof. it's another project on Github and contains all the more expensive regression tests. Lots of tests involving 3rd party data sets. A few unit tests in BoofCV uses a simplistic 3D scene generator to test algorithms. This is done more in fiducial markers.

One area that could use extra help is implementing a more recent Pose-N-Point (PNP) algorithm. I've got a few that need to be done.

**Comment by automenta** [comment]
ValidationBoof yes i can see what you mean there.  im still confused how the PNP and Bundle Adjustment differ and how much they share or can share in common.  a quick search for sparse bundle adjustment code found this https://github.com/balintfodor/sba which seems translateable into boofcv's matrix math ops

btw on the multiview construction, i got a big speed boost by switching from the greedy associator to the kd-tree.  
    static final int SURF_DIMENSIONS = 64;

but without more robust validation or visualization i cant tell if the quality degraded since the pipeline cant produce more than the cloud of points so detail is fuzzy.  using the chair set of images, it still produces more or less the right shape blob.  my current code is here, kept in the same demo class.  im using an opengl viewer for the pointcloud.  this will need to be extended to mesh geometry rather than drawing just the points.

https://github.com/automenta/narchy/blob/skynet5/lab/src/main/java/spacegraph/slam/ExampleMultiviewSceneReconstruction.java#L673

also looking to make the model resolution iterative/progressive so it gradually resolves more detail, and can also forget detail if the model changes while it all remains live and realtime.  the resulting detail would depend on how much the input changes and how long it has to resolve further detail.  it can allow input by camera(s) as they would just append new image frames to the model, asynchronously.  

this will require changing the dense association matrix to a sparse graph that can be used to cull images that have become sufficiently disconnected from the core of the scene (ex: by graph centrality).  the graph nodes and edges will contain useful heuristic statistics that can guide the iterative updating.  for example the association weights between images would prioritize the processing of image pairs.  another quick improvement was to make the cut-off threshold a percentile so it becomes a quality parameter independent of the associator implementation's weight scoring
        connectThreshold = weights.getValueAtPercentile(connectPercentile);

**Pull request closed without merging**
