### PR TITLE
Search box

### PR DESCRIPTION
**Pull request by jmankhan**
Down arrow goes to next search match
Up arrow goes to previous search match
Enter opens app.

Searches by first exact match containing term

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
could you add the following?

- move the scroll bar so that the selected element is visible when typing.  This already happens when using the arrows
- Add the word "Search" to the left of the search box so that people know what it is

**Comment by lessthanoptimal** [comment]
Also noticed that you removed the monospaced font.   Any reason for that?  Code is formatted with the assumption that the font is monospaced.

Not really sure what's going on with a partial revert dealing with JSplitPanels around line 205.  Was that intentional?

I would compare both of these against de9c433edd2fdbd5cb5f48d6a99ee272e5551a04 (my last commit)

**Comment by jmankhan** [comment]
Sorry! I think I merged from upstream poorly. I'll fix it and commit tonight

**Comment by lessthanoptimal** [comment]
Having trouble sleeping so I just did the last bit of work.  merged!

**Pull request merged**
