### PR TITLE
ConfigureSquareGrid use number of squares for cols and rows

### PR DESCRIPTION
**Pull request by thhart**
As discussed this is a change for ConfigureSquareGrid using the number of squares. Checked for most examples still working correct. To be reviewed finally, documentation still pending.

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
Could you also update ValidationBoof?  That's were regression tests lie.  It's not documented very well so I might need to add instructions on how to run it first.

**Comment by thhart** [comment]
Where to find, which repo? Will check, but not before end of week.

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/ValidationBoof

I'll update the readme to include better instructions, but a good place to start is GenerateRegressionData.  That's the master class which runs all the tests.  Then look for anything with fiducial or calibration in its name.

There are text configuration files which will need to be modified to use the new format

**Comment by lessthanoptimal** [comment]
I also notice that it's saying this pull reflect has a conflict.  Did you use the latest code?

**Comment by thhart** [comment]
Will request again after merge.

**Pull request closed without merging**
