### PR TITLE
Adds ability to project bands of a planar image into a single image

### PR DESCRIPTION
**Pull request by nicost**
This code adds the ability to project a range of bands in a planar image into a single image.  Currently, average, median, minimum, maximum, and standard deviation projections are supported.  These types of projections are useful in analysis or display of time series or through-focus series of images.  I placed these functions in its own class, but are completely happy with any other organization within the existing code.  When defining the range of bands, the last band will be included in the projection.

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
Could you rename it to something like ImageBandMath? ProjectionMath will really confuse people working on projective geometry and think it has to deal with projecting a 3D point onto an image.

The other issue is that the code isn't auto generated. I can rewrite it to be auto generated but that will delay it being accepted. See GenerateImageMiscOps for an example of how to generate code. I realize that writing classes like that is a beast. I'm open to suggestions on how to improve the situations. I typically write a function like you did, past it into the generator, and modify it for different image types. If that looks too complex for you I'll just do it some time in the future.

**Comment by nicost** [comment]
I'll rename the classes.  Funny how people's varying backgrounds/domains lead to varying nomenclatures, and very good to discuss this!  The term Projection indeed arose because most often collections of images (image stacks) represent actual 3D volumes and projecting them at a 0 degree angle onto a single plane is a fast and easy way to project them.  It is a special case of a projection, and you already use the term "bands", so I am fine with ImageBandMath (will change).

I'll look into auto generating the code.  It may take me some time, but will be worthwhile to figure it out. Having the tests ready will be very helpful.

The Travis build failed for this PR.  I looked into the output, but it is unclear how (and if) the error relates to the PR.

**Comment by lessthanoptimal** [comment]
Could you add my name to the copyright notice? Feels weird asking for that, but BoofCV does not exist as a legal entity and if code donations become regular enough I'll fix that.

**Comment by nicost** [comment]
Renamed the classes and added the copyright notice.  Have not looked at code generation yet, but looking forward working that out.

**Pull request merged**
